package setting

type fieldExportColumn struct {
	Key   string
	Title string
	Width float64
}

var fieldExportFieldColumns = []fieldExportColumn{
	{Key: "object_name", Title: "业务对象", Width: 14},
	{Key: "object_code", Title: "对象编码", Width: 18},
	{Key: "source_type", Title: "字段来源", Width: 14},
	{Key: "template_id", Title: "模板ID", Width: 12},
	{Key: "template_name", Title: "数据模板", Width: 24},
	{Key: "template_status", Title: "模板状态", Width: 12},
	{Key: "parent_field", Title: "父字段", Width: 20},
	{Key: "field_path", Title: "字段路径", Width: 34},
	{Key: "field_id", Title: "字段ID", Width: 12},
	{Key: "field_name", Title: "字段名称", Width: 24},
	{Key: "field_code", Title: "字段编码", Width: 34},
	{Key: "field_type_code", Title: "字段类型编码", Width: 18},
	{Key: "field_type_name", Title: "字段类型", Width: 16},
	{Key: "finance_type_code", Title: "财务类型编码", Width: 22},
	{Key: "finance_type_name", Title: "财务类型", Width: 22},
	{Key: "stat_enabled", Title: "参与统计", Width: 12},
	{Key: "storage", Title: "存储位置", Width: 38},
	{Key: "default_value", Title: "默认值", Width: 22},
	{Key: "field_status", Title: "字段状态", Width: 12},
	{Key: "sort", Title: "字段排序", Width: 12},
	{Key: "feishu_table", Title: "飞书表名", Width: 22},
	{Key: "feishu_field", Title: "飞书字段名", Width: 22},
	{Key: "match_status", Title: "匹配状态", Width: 14},
	{Key: "remark", Title: "备注", Width: 30},
}

var fieldExportOptionColumns = []fieldExportColumn{
	{Key: "object_name", Title: "业务对象", Width: 14},
	{Key: "source_type", Title: "字段来源", Width: 14},
	{Key: "template_name", Title: "数据模板", Width: 24},
	{Key: "field_name", Title: "字段名称", Width: 24},
	{Key: "field_code", Title: "字段编码", Width: 34},
	{Key: "option_source", Title: "选项来源", Width: 18},
	{Key: "option_set_name", Title: "选项集", Width: 24},
	{Key: "option_name", Title: "选项名称", Width: 24},
	{Key: "option_value", Title: "选项值", Width: 26},
	{Key: "option_status", Title: "选项状态", Width: 12},
	{Key: "sort", Title: "选项排序", Width: 12},
}

var fieldExportWorkflowColumns = []fieldExportColumn{
	{Key: "object_name", Title: "流程对象", Width: 14},
	{Key: "object_code", Title: "对象编码", Width: 18},
	{Key: "workflow_id", Title: "流程ID", Width: 12},
	{Key: "workflow_name", Title: "流程名称", Width: 22},
	{Key: "default_entry", Title: "默认入口", Width: 12},
	{Key: "workflow_status", Title: "流程状态", Width: 12},
	{Key: "workflow_sort", Title: "流程排序", Width: 12},
	{Key: "stage_id", Title: "阶段ID", Width: 12},
	{Key: "stage_name", Title: "阶段名称", Width: 22},
	{Key: "stage_assignment_mode", Title: "阶段分配方式", Width: 20},
	{Key: "stage_owner_department_id", Title: "阶段负责部门ID", Width: 18},
	{Key: "stage_status", Title: "阶段状态", Width: 12},
	{Key: "stage_sort", Title: "阶段排序", Width: 12},
	{Key: "task_id", Title: "任务ID", Width: 12},
	{Key: "task_name", Title: "任务名称", Width: 24},
	{Key: "task_type", Title: "任务类型", Width: 16},
	{Key: "required", Title: "是否必做", Width: 12},
	{Key: "assignee_mode", Title: "负责人规则", Width: 24},
	{Key: "assignee_department_id", Title: "任务负责部门ID", Width: 18},
	{Key: "form_id", Title: "表单ID", Width: 12},
	{Key: "form_name", Title: "关联表单", Width: 24},
	{Key: "script_id", Title: "核验规则ID", Width: 14},
	{Key: "activation_mode", Title: "创建方式", Width: 18},
	{Key: "reject_action", Title: "驳回处理", Width: 18},
	{Key: "reject_target_task_id", Title: "驳回目标任务ID", Width: 18},
	{Key: "complete_target_task_id", Title: "完成目标任务ID", Width: 18},
	{Key: "opinion_requirement", Title: "审核意见规则", Width: 18},
	{Key: "reject_submit_form", Title: "驳回提交资料", Width: 16},
	{Key: "communication_group_enabled", Title: "建沟通群", Width: 14},
	{Key: "due_days", Title: "办理期限天数", Width: 14},
	{Key: "task_status", Title: "任务状态", Width: 12},
	{Key: "task_sort", Title: "任务排序", Width: 12},
}

var fieldExportReferenceColumns = []fieldExportColumn{
	{Key: "object_name", Title: "业务对象", Width: 14},
	{Key: "workflow_id", Title: "流程ID", Width: 12},
	{Key: "workflow_name", Title: "流程名称", Width: 22},
	{Key: "stage_id", Title: "阶段ID", Width: 12},
	{Key: "stage_name", Title: "阶段名称", Width: 22},
	{Key: "task_id", Title: "任务ID", Width: 12},
	{Key: "task_name", Title: "任务名称", Width: 24},
	{Key: "form_id", Title: "表单ID", Width: 12},
	{Key: "form_name", Title: "表单名称", Width: 24},
	{Key: "form_status", Title: "表单状态", Width: 12},
	{Key: "form_field_id", Title: "表单字段ID", Width: 14},
	{Key: "form_field_name", Title: "表单字段名称", Width: 24},
	{Key: "source_type", Title: "字段来源", Width: 14},
	{Key: "template_id", Title: "模板ID", Width: 12},
	{Key: "template_name", Title: "数据模板", Width: 24},
	{Key: "field_id", Title: "字段ID", Width: 12},
	{Key: "field_code", Title: "字段编码", Width: 34},
	{Key: "field_path", Title: "字段路径", Width: 40},
	{Key: "finance_type_code", Title: "财务类型编码", Width: 22},
	{Key: "finance_type_name", Title: "财务类型", Width: 22},
	{Key: "stat_enabled", Title: "参与统计", Width: 12},
	{Key: "required", Title: "是否必填", Width: 12},
	{Key: "readonly", Title: "是否只读", Width: 12},
	{Key: "field_status", Title: "引用状态", Width: 12},
	{Key: "sort", Title: "引用排序", Width: 12},
}
